version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 30
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
  registries:
  - npm-registry-npm-pkg-github-com
