name: API Client publish

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=NPM_TOKEN::${{secrets.GITHUB_TOKEN}}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Lint & Build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@oacore/configs'
      - run: |
          npm ci

      - name: Bump version ${{ steps.get_version.outputs.VERSION }}
        run: npm run version ${{ steps.get_version.outputs.VERSION }} -- --git-tag-version=false  --force-publish --yes

      - name: Publish package
        run: npm run publish -- --registry='https://npm.pkg.github.com' --yes

